# Generated by Django 4.1 on 2022-08-17 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_university_alter_student_university'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funding',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='created_at',
            new_name='date_created',
        ),
    ]
